### ISSUE TITLE
Better support for symlinks

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-files#10]
In current version of cosmic-files, I can open the symlink directories but they've wrong icons & the size details.
Here is a screenshot in cosmic-files & nautilus:
![image](https://github.com/pop-os/cosmic-files/assets/58325574/2fa2bde3-30d7-455f-bfcd-04f6ab74f293)

**Comment by senntore** [comment]
Currently the search results are also not showing files & directories that are inside sysmlink. 
So, if we were to search in home directory(from the above screenshots), for a file that is inside one of the sysmlink, then the search results should be showing those files. but it is not showing them right now. 
Gnome's File manager does show results for them, so maybe it's worth adding the feature to Cosmic files as well.

**Comment by zsilet** [comment]
A couple of additional notes (as of Alpha1):

1. Clicking a symlinked directory launches a new instance of COSMIC files (should just follow the link)
2. (Not sure if related) In VSCode, when attempting to open a project from a folder, when I get to a symlink, there is no way to 'follow' it. Clicking the link automatically opens that folder as the project folder.

**Comment by zsilet** [comment]
Thanks, will keep an eye on it.

**Comment by zsilet** [comment]
Verified that my issue 2 is now fixed (Symlinked directories show as directories, and are followed, in VScode's open folder dialog). Thanks!

**Comment by WatchMkr** [comment]
Closing this issue and tracking adding a badge here: https://github.com/pop-os/cosmic-files/issues/466
