### ISSUE TITLE
Issues with dragging files to the navigation bar 

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-files#107]
Drag and drop works pretty well for a freshly merged feature. But the dragging to the navigation bar has some issues.

- Dragging and dropping a file into a directory in the navigation bar just copies it.
- Dragging a file into a child directory works, but there is no way to go back to the parent directory. Dragging and pausing over the address bar doesn't work.
- Dragging and pausing over the directories in the navigation bar would show the content of that directory but doesn't really `cd` into it. The address bar still will show the previous directory. 
![screenshot-2024-04-11-12-39-48](https://github.com/pop-os/cosmic-files/assets/2222199/3166c162-b5a0-463b-ab6d-9327800ab5e3)

**Comment by WatchMkr** [comment]
There are a few issues here that we'll prioritize separately.

> Dragging and dropping a file into a directory in the navigation bar just copies it.

This is now working but there are general cut/copy/paste issues that we'll track [here](https://github.com/pop-os/cosmic-files/issues/90).

> Dragging a file into a child directory works, but there is no way to go back to the parent directory. Dragging and pausing over the address bar doesn't work.

Going to track this feature request here: https://github.com/pop-os/cosmic-files/issues/177

> Dragging and pausing over the directories in the navigation bar would show the content of that directory but doesn't really cd into it. The address bar still will show the previous directory.

Going to track this one here: https://github.com/pop-os/cosmic-files/issues/178
