### ISSUE TITLE
Feature: add file previews

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-files#109]
File preview should open simultaneously with selecting folder or file by clicking on it. 
![Home-grid-preview](https://github.com/pop-os/cosmic-files/assets/57502897/bdd81ca1-28af-466f-b836-ed57dcdfec84)
[Figma mockups. ](https://www.figma.com/file/ZBg577prx1KF8BlZrBSgT0/Files?type=design&node-id=2302-38542&mode=design&t=hDZWaM9A5mNBhDqD-4)

**Comment by cd-CreepArghhh** [comment]
Maybe also details *specific to the file type* (e.g. video length, image size) under the preview, kinda like Dolphin (KDE)?

**Comment by M00NJ** [comment]
I've seen a (harsh) complaint about the file preview overlapping the content view which makes navigating through files with the keyboard difficult in this video: https://youtu.be/KP3dOUJgng0&t=136 
I don't have a suggestion how to solve this. Just thought to mention it here. Timestamp is included in the link.

**Comment by guilhermeaiolfi** [comment]
> One easy fix for this I can think of is to shrink the content view when the file preview is opened so the two layers don't overlap.
It's worth mentioning that if that's the fix system76 is going after, the grid view will change considerable with previews. If you open and close the preview, it will do quite a dance for the user to see.

**Comment by maria-komarova** [comment]
The designs for File previews have been updated. The layout should follow the pattern where ContextDrawer opens next to the content area making the content re-flow. The behavior and responsiveness is described [here](https://www.figma.com/design/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=22365-19197&t=oqEDDbG4p60HWMut-4) in the Design System. 

Small video demonstrating how the app should shrink. 

https://github.com/user-attachments/assets/9654bd93-f146-405e-9e7b-977effeb0220

Another video shows the interaction with the file preview when the content area is at its minimum width. 

https://github.com/user-attachments/assets/8bb52681-d243-4d21-a3a3-2b0e30366231

[Mockups used for the prototypes](https://www.figma.com/design/mhNOAitgqyZriInNN0v0sw/Layout-resizing?node-id=223-44499&t=xebuMolIVJLDSmsz-1).
