### ISSUE TITLE
Feature: functionality to empty the Trash folder

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-files#110]
![Trash](https://github.com/pop-os/cosmic-files/assets/57502897/e68f886b-7be0-494a-995f-55cedf42ab1e)
[Mockups in Figma](https://www.figma.com/file/ZBg577prx1KF8BlZrBSgT0/Files?type=design&node-id=2307-7100&mode=design&t=hDZWaM9A5mNBhDqD-4).

**Comment by cd-CreepArghhh** [comment]
Maybe red button to symbolise danger?

The same mockup could probably be copied for permanently deleting a single file from the trash.

**Comment by jackpot51** [comment]
Implemented in https://github.com/pop-os/cosmic-files/commit/1116eaa05ab9cbb452eb3c65abde4a422a1f2115, which accidently tagged another issue
