### ISSUE TITLE
Functionality to add and remove items from the NavBar (Sidebar in the UI)

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-files#112]
Relevant mockups: context menu for the items in the NavBar and a menu item "Add to sidebar" in various menus and context menus. 
![screenshot-2024-04-12-15-23-21](https://github.com/pop-os/cosmic-files/assets/57502897/861df6ac-7d03-4439-9c3d-69e5cb6e0c1f)
[Mockups](https://www.figma.com/file/ZBg577prx1KF8BlZrBSgT0/Files?type=design&node-id=2308-56079&mode=design&t=hDZWaM9A5mNBhDqD-4).

**Comment by mmstick** [comment]
Requires https://github.com/pop-os/libcosmic/issues/395
