### ISSUE TITLE
Select multiple items using Shift and click

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-files#114]
Click on one item, hold Shift and then click on another item should select the items in between the two clicked items.

**Comment by MohammadShabaniSBU** [comment]
Hi, I am trying to implement this feature, but I noticed that when a click event is triggered, the match arm for Message::Click executes twice. I want to know if it is a bug or something that you implemented.

**Comment by jasonrhansen** [comment]
@MohammadShabaniSBU I noticed the same issue where the Click event would fire twice. I fixed it in my first commit of #193.
