### ISSUE TITLE
Drag and drop to move items

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-files#116]
It is partially implemented. 

There are a few remaining issues:
- Dragging to a NavBar or a tab switches the folder view but doesn't change the breadcrumb.
- Doesn't look like the item is moved or copied (when I try it) when dragging to the NavBar or the tab.
- Dragging over the same folder shows an error dialog about failing to copy the item - I don't think we need one. Just switch to the originating folder view. Nothing else is needed, the item that was being dragged could still be highlighted. 
- When dragging from the child folder to the parent folder the parent folder is highlighted after the view has switched. Probably not necessary. The item currently is not moved after the mouse release.
 
#107 is related.

**Comment by jackpot51** [comment]
This needs to be retested, a couple fixes for drag and drop were recently merged.
