### ISSUE TITLE
COSMIC Files MVP Issue List

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-files#118]
- [ ] #109 
- [x] #113 
- [ ] #86 
- [x] #114 
- [x] #116 
- [x] #110 
- [x] #90 
- [x] #7
- [x] #40 
- [x] #112 
- [ ] https://github.com/pop-os/cosmic-files/issues/165
- [x] https://github.com/pop-os/cosmic-files/issues/179
- [x] https://github.com/pop-os/cosmic-files/issues/180
- [x] https://github.com/pop-os/cosmic-files/issues/171
- [x] https://github.com/pop-os/cosmic-files/issues/189

**Comment by WatchMkr** [comment]
Removed META: Various touch screen issues because touch screens aren't a Epoch 1 target. https://github.com/pop-os/cosmic-files/issues/62

**Comment by WatchMkr** [comment]
Removed Match "Open with" to the design. The current functionality works well enough for a first release.

**Comment by WatchMkr** [comment]
Removed Rename folder and file experience for now. https://github.com/pop-os/cosmic-files/issues/115

**Comment by WatchMkr** [comment]
Added "Recents" feature.

**Comment by WatchMkr** [comment]
Added Search

**Comment by WatchMkr** [comment]
Added file conflict dialogs.

**Comment by WatchMkr** [comment]
Removed [Menus](https://github.com/pop-os/cosmic-files/issues/5) and added [View Menu and feature MVP ](https://github.com/pop-os/cosmic-files/issues/184) and https://github.com/pop-os/cosmic-files/issues/183 to reduce scope a bit.

**Comment by WatchMkr** [comment]
We need to fix breadcrumb responsiveness for the alpha. Added  "[Alternative single-column breadcrumb design](https://github.com/pop-os/cosmic-files/issues/189)" which needs design discussion.

**Comment by WatchMkr** [comment]
Tracking via MVP via milestones.
