### ISSUE TITLE
[Feature Request] Compress/Extract Options

### ISSUE THREAD

**Issue by nathansgithub** [pop-os/cosmic-files#122]
One feature I really like in Nautilus is the right-click archive options, and I would love if you could replicate that here.

This is the "Extract Here" and "Extract to" options on various formats of zipped/archive file, and the "Compress" option on any one or more selected files.

**Comment by nathansgithub** [comment]
If you all are willing to merge this, I might take a stab at coding these.

**Comment by WatchMkr** [comment]
@nathansgithub this is a feature we'd merge if implemented.

**Comment by WatchMkr** [comment]
Secondary click options:

Compress
Extract
Extract to...

MVP for compress > make a .zip archive in the current directory. MVP+1 password protected zip archives with dialog for choice and name.

**Comment by iamkartiknayak** [comment]
This feature is needed ASAP. I'm tired of launching terminal every-time to extract a compressed file.

**Comment by nathansgithub** [comment]
I made a PR for an MVP to handle extracting .zip files to the current directory: https://github.com/pop-os/cosmic-files/pull/370

Adding dialogues for the other pieces will be a little more involved, and I'm not sure what the preferred way to handle other archive types would be, but I think this piece is useful by itself.
