### ISSUE TITLE
Cosmic Files Crashing

### ISSUE THREAD

**Issue by fuyo2** [pop-os/cosmic-files#134]
Found a bug with Cosmic Files crashing. 

Steps to reproduce:

1. Launch Cosmic Files
2. Click 'Trash'
3. Go to 'View --> About COSMIC Files...'
4. Click 'Close' on the about panel
5. Click 'Documents'

Cosmic Files crashes every time. Let me know if there is any other information you need.

**Comment by WatchMkr** [comment]
I'm not able to reproduce this. Is it still occurring?

**Comment by fuyo2** [comment]
> I'm not able to reproduce this. Is it still occurring?

No, on my few test machines, this seems to no longer be an issue. Looks like there have been a few updates since I reported this.

**Comment by WatchMkr** [comment]
Thanks for the reply!
