### ISSUE TITLE
[Bug] files with very long names can't be moved to the trash bin

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-files#140]
If the file names are too long, files can't be moved to the trash bin.

**Comment by WatchMkr** [comment]
Can you provide a file name example? I'm not able to reproduce this.

How are you moving the file to the Trash bin?

**Comment by onlyreportingissues** [comment]
> Can you provide a file name example? I'm not able to reproduce this.
> 
> How are you moving the file to the Trash bin?

I wasn't able to reproduce it, but maybe https://github.com/pop-os/cosmic-files/issues/142 can be helpful.
