### ISSUE TITLE
[Feature Request] right-click context menu a file -> allow to be executed as a program (e.g. .sh file)

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-files#147]
It would allow to make scripts, AppImages etc. runnable as executables using COSMIC Files.

**Comment by WatchMkr** [comment]
tracking here: https://github.com/pop-os/cosmic-files/issues/23

**Comment by Mershl** [comment]
want to avoid creating a duplicate issue. #23 does not cover executeable .sh files, right? (tested myself on alpha6)
