### ISSUE TITLE
bug: icon lookup failing to find correct icons.

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/cosmic-files#150]
When the grid icon size is set to 125% and the app is restarted afterwards, these icons appear, which are not the correct icons.

![screenshot-2024-05-09-13-45-01](https://github.com/pop-os/cosmic-files/assets/22224438/95153d19-3ab9-4b04-9bb2-0d32eaf0589f)

**Comment by onlyreportingissues** [comment]
List view is also affected, if anything besides 100% & 200% is chosen.

**Comment by WatchMkr** [comment]
This appears to be fixed.
