### ISSUE TITLE
Arrow keys navigation does not scroll the view below

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-files#164]
The directory view is fixed to top(or it's current position) when using arrow keys to select applications & doesn't scroll below.
So we cannot see the selected item if we keep using arrow keys.
Note: It works when going navigating above but not below.

I've also seen this issue in application library https://github.com/pop-os/cosmic-applibrary/issues/98

**Comment by jackpot51** [comment]
Going up is working but not going down, I will look into it.
