### ISSUE TITLE
Feature Request: "Recents" section

### ISSUE THREAD

**Issue by nebrelbug** [pop-os/cosmic-files#165]
I use the "Recent" section in Gnome files all the time. When I run macOS and Windows, I use it all the time too. It's especially helpful after downloading a file from the internet.

**Comment by francesco-gaglione** [comment]
I can work on it, I opened a similar pull request for bookmarks. Just one question for more cosmic expert people... It is easy to track "recent" files by trucking the user actions, but it is impossible to track them outside the cosmic file app. Do we have some libcosmic (or other) utility to retrieve recent files? My question is to avoid file system tree scan to search recent files based on dates.

**Comment by mmstick** [comment]
@francesco-gaglione We made this a while back: https://crates.io/crates/recently-used-xbel

**Comment by francesco-gaglione** [comment]
@mmstick oh great, I did it from scratch. I will replace it with this and open a pull request.
