### ISSUE TITLE
Copying a file and pasting it to a different directory doesn't work

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-files#168]
If the file is Cut, or is pasted in the same directory, there are no errors. Copying directories works properly.
![screenshot-2024-05-20-22-43-40](https://github.com/pop-os/cosmic-files/assets/150025636/1453369a-5373-4651-bb19-d5b6caef9447)

**Comment by WatchMkr** [comment]
We have general cut/copy/paste issues and tracking them here: https://github.com/pop-os/cosmic-files/issues/90
