### ISSUE TITLE
Feature req: Show full name of file/directory when highlighted

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-files#169]
Current behavior:

![screenshot-2024-05-21-03-04-39](https://github.com/pop-os/cosmic-files/assets/56272643/a1dc0e58-844d-48df-95f5-e1f91423b2c4)

My workflow currently consists of changing the view to list view every time I need to see the full name of something.

**Comment by maria-komarova** [comment]
The idea is to show long file names in a tooltip on hover. Here is a [quick prototype for illustration](https://www.figma.com/proto/ZBg577prx1KF8BlZrBSgT0/Files?node-id=3984-70414&node-type=FRAME&t=5fillgcdCJKFg43h-1&scaling=min-zoom&content-scaling=fixed&page-id=2301%3A33940&starting-point-node-id=3984%3A70414&show-proto-sidebar=1). 
[Figma mockups](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=3984-69444&m=dev).
