### ISSUE TITLE
Drag into the breadcrumb bar

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#177]
Ability to drag files and folders into the breadcrumb bar similar to the NavBar. Hovering opens the directory. Dropping cuts and paste into the new directory. 

We need design for how the on-hover directory should appear.

**Comment by WatchMkr** [comment]
This enables a users to more easily go backward to a previous directory. For instance:

Drag a file from Directory1 > SubDirectory1 > SubDirectory2
Currently can't get back to SubDirectory1 without trying to cancel and starting over.

**Comment by maria-komarova** [comment]
The mockup showing the drop-target state for the breadcrumb link ([link to Figma](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=3064-28672&t=0g8ZMxb9wpr2SMFL-4)):
![Drop-target-breadcrumb](https://github.com/pop-os/cosmic-files/assets/57502897/bc5252d0-1c99-4d96-b18e-f4d180385682)

**Comment by WatchMkr** [comment]
Ready for development.

**Comment by afonsorek** [comment]
Hey, I am interested in helping with this one, is it open to work on?

**Comment by WatchMkr** [comment]
@afonsorek absolutely. Thanks for contributing.
