### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#179]
![screenshot-2024-05-25-18-46-11](https://github.com/pop-os/cosmic-files/assets/3430283/5276a6aa-6d84-4dac-842b-bf9819532007)
![screenshot-2024-05-25-18-46-01](https://github.com/pop-os/cosmic-files/assets/3430283/0d4a9f21-44df-43a2-89cb-f9b1dad07180)

[Design file](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=2301-33940&t=t6IJPMjLnszwrKs0-0)

**Comment by jackpot51** [comment]
This was implemented in #215. I re-used the tab infrastructure so it shows up as a tab, with identical capabilities (sorting, opening files). This should be looked at and smaller issues created for what remains.
