### ISSUE TITLE
Alternative single-column breadcrumb design

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#189]
As the breadcrumb path doesn't fit a single line, remove directories at the front of the directory (Home first) down until it's the current directory. At a single column, ellipses the final directory if the name doesn't fit. Leave back/forward and path edit.

**Comment by maria-komarova** [comment]
The updated mockup:
![Default-Light-Single-column](https://github.com/pop-os/cosmic-files/assets/57502897/6b26b945-f4f7-4768-8578-3820ce0bdecc)

**Comment by WatchMkr** [comment]
Ready for development along with https://github.com/pop-os/cosmic-files/issues/177
