### ISSUE TITLE
Add Sort menu to the Menu bar

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#192]
![image](https://github.com/pop-os/cosmic-files/assets/3430283/12d2ae98-a107-4f6e-9d53-785a359796cd)

**Comment by WatchMkr** [comment]
More options are likely needed     A-Z
    Z-A
    Last modified
    First modified
    Size
    Type

**Comment by WatchMkr** [comment]
Should we include the sort button in list view?

**Comment by WatchMkr** [comment]
Problem > can't sort in narrow width. Current suggested location is valuable space for directory names.

**Comment by maria-komarova** [comment]
Add Sort menu item to the Menu bar in the window header. The item should collapse under the Menu item in single-column view.
![Home-grid (2)](https://github.com/user-attachments/assets/7ac07397-2e24-4841-a49c-987c7c9d7339)
The menu:
![Menu-Sort-by](https://github.com/user-attachments/assets/11f79b14-a740-497d-a66d-2db2cd7c2240)

**Comment by TheESN** [comment]
![Image](https://github.com/user-attachments/assets/3cdeeab1-3b0d-4f58-b06f-122d8db3f031)

In file picker will sort button be as the single menu bar option?

**Comment by maria-komarova** [comment]
No, file picker will use dropdown menus with icons in the right corner. 
![Open-file (2)](https://github.com/user-attachments/assets/9b71769e-faf3-4cb2-b78a-5d97d5b77645)
More details in the [mockups](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=2309-57396&t=yKOENxPumM43PYJd-4).
