### ISSUE TITLE
Browsing to network shares

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#202]
- [x] Add network drive button, context page, and dialogs
- [x] Add table of supported protocols to network drive context page
- [ ] Networks folder implementation

**Comment by MrGamerDoesGames** [comment]
WebDAV support alongside this would be nice.

**Comment by jacobgkau** [comment]
In Nautilus and Dolphin, I can enter an SFTP address starting with `sftp://` in the path bar to connect. This currently just opens Firefox (which doesn't handle that protocol, anyway).

**Comment by WatchMkr** [comment]
Potential protocols to support
AppleTalk afp://
FTP ftp:// and ftps://
NFS nfs://
Samba smb://
SSH sftp:// ssh://
WebDAV dav:// davs://

**Comment by maria-komarova** [comment]
[The link to Figma mockups](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=3909-57501&t=F5lrC73BywemmEKN-4).
