### ISSUE TITLE
Global search feedback

### ISSUE THREAD

**Issue by leb-kuchen** [pop-os/cosmic-files#224]
Overall search time is a bit slower than fd with --no-ignore and the --ignore-case the flags, but still competitive. 

- [x] Hidden files are not included,  regardless of  the`Show hidden files` setting.
- [x] The search results are not displayed during the search process. Updating the search results in the view may delay the overall search significantly, though it might not be worth doing.

**Comment by jackpot51** [comment]
I do want to stream the results, but I worry about how they are sorted. Streaming means new results will come in that may reorder the list.

**Comment by leb-kuchen** [comment]
If I recall, the results are sorted in the view.

I think the best way to go about it, is a refresh button, if new search search result are available.

**Comment by jackpot51** [comment]
Implemented hidden files toggle for search in 28b4dda7e00d9c79fdea295d39491b3c3c8dea84
