### ISSUE TITLE
[Feature Request] Run executables

### ISSUE THREAD

**Issue by Vixea** [pop-os/cosmic-files#23]
Many file managers allow launching executables from them.
For example I have a few appimages in a location where launching them from a GUI application is faster than a terminal

**Comment by Vixea** [comment]
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
This is the missing permission it seems

**Comment by francesco-gaglione** [comment]
@Vixea  I'm considering to work on this. In the meantime take a look to this, you can run apps from gui and if installed with this app you will have the app in the desktop launcher

https://github.com/cosmic-utils/AppHub
