### ISSUE TITLE
[Feature Request] - Option to create a new folder in Open Folder Dialog

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/cosmic-files#231]
Example of GTK FilePicker doing this:

![Screenshot from 2024-06-05 13-20-37](https://github.com/pop-os/cosmic-files/assets/4884946/54509937-d285-4e49-b609-e9f83be19675)

When you save a file (or open a folder) there is a plus icon in the top right to create a new folder (and name it) from that window. My use case of needing it is for Stellarshot where we create a new repository but need a prompt to create that folder for the repo and name it.

**Comment by TheESN** [comment]
It's already planned in their figma designs

**Comment by WatchMkr** [comment]
Closing this but will create a new issue with the design to track.
