### ISSUE TITLE
[Suggestion] Do not show image previews in the "Open with" window

### ISSUE THREAD

**Issue by PoisonFrog** [pop-os/cosmic-files#236]
Right now it shows image previews in the "Properties" and "Open with" windows and while it makes sense to have it in Properties where you can quickly tap space to see a preview, it is annoying to have it in the "Open with" pane when you are in floating mode and do not have a big application window. Now I have to scroll down every time I try to open an image with an application other than the default one. When I click "Open with" I just want to see my options, not an image preview that takes up all the space.

**Comment by jackpot51** [comment]
It is a copy of the properties page, which will be replaces as part of #111

**Comment by PoisonFrog** [comment]
> It is a copy of the properties page, which will be replaced as part of #111

Alright, I'm closing this issue then.
