### ISSUE TITLE
Local search option and drag and drop option

### ISSUE THREAD

**Issue by Coder-Vasen** [pop-os/cosmic-files#251]
I am new to cosmic environment. I tried to search for `Users` folder which is a windows drive folder, then the cosmic files application opened the new tab of application and searched for `Users` in home directory.

Before searching:
![Screenshot-4](https://github.com/pop-os/cosmic-files/assets/69237691/051abf0e-9602-42db-a0d3-f3c65729b1f6)

After searching:
![Screenshot-5](https://github.com/pop-os/cosmic-files/assets/69237691/4f4cbcda-d5bb-4bc3-95be-2b91bca1b82a)

It's not only for the external devices tho. It is showing the results globally.

While uploading the screenshots for the first issue got the other one, I couldn't able to drag and drop the files.

**Comment by jackpot51** [comment]
This was already implemented, what version are you running?

**Comment by Coder-Vasen** [comment]
> This was already implemented, what version are you running?

It's showing Git commit `c639d6d` on 2024-06-05

**Comment by jackpot51** [comment]
This was implemented in https://github.com/pop-os/cosmic-files/commit/0ec5f72169f32b29d595fbae95d5e54e8cd2cd2f on June 10.

**Comment by jackpot51** [comment]
That depends on what distro you are using. If you are on Pop!_OS, just wait for updates.
