### ISSUE TITLE
Deletion of files in "find" view doesn't update view

### ISSUE THREAD

**Issue by flukejones** [pop-os/cosmic-files#252]
Per title really.

1. Do a `ctrl+f` for search, and search for something to delete
2. Select any of these to delete and do so
3. The view does not update to reflect removal
4. Select the files and try to delete again to see error message
5. Do a search again for the same files and see that they really were deleted

**Comment by l-const** [comment]
Should be closed by: https://github.com/pop-os/cosmic-files/pull/437
