### ISSUE TITLE
Give option to overwrite (or use different name) when pasting a file that already exists

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-files#253]
Currently, if I try to paste a file into a directory that already contains a file with the same name, I just get an error message:

![screenshot-2024-06-17-22-27-31](https://github.com/pop-os/cosmic-files/assets/7199422/86d3ad90-6087-4425-bbae-65532ca5f348)

I should be given the option to overwrite the destination or cancel (or probably also to paste the file with a different name).

**Comment by M00NJ** [comment]
#180
