### ISSUE TITLE
Main area context menu doesn't go away on left-click in empty folder

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-files#289]
In a normal folder, if I right-click somewhere and then left-click in an empty space, the context menu goes away.

https://github.com/user-attachments/assets/06245509-73cd-478c-a0f7-2ab9abdf7961

In an empty one, the context menu doesn't close on a left-click in the main content area; only a right-click (or ESC) closes it.

https://github.com/user-attachments/assets/30740fb1-2403-43be-bae9-a41d7aebffb7

It's a little hard to show in a screencast, so hopefully the description makes sense.

**Comment by WatchMkr** [comment]
This appears to be fixed.

**Comment by jacobgkau** [comment]
This particular case is gone, but other cases still remain: https://github.com/pop-os/cosmic-files/issues/328
