### ISSUE TITLE
Size is not updated in settings page when Ctrl plus or Ctrl minus are used

### ISSUE THREAD

**Issue by TheESN** [pop-os/cosmic-files#291]
![изображение](https://github.com/user-attachments/assets/adca97a7-f68e-478d-b412-214b45a316fe)

**Comment by WatchMkr** [comment]
This is because settings in the View menu currently only changes the current directory view. This will be changed so that settings in the View menu are for the app. See https://github.com/pop-os/cosmic-files/issues/321
