### ISSUE TITLE
Problem with uploading files caused by address bar

### ISSUE THREAD

**Issue by VandaLHJ** [pop-os/cosmic-files#298]
![screenshot-2024-07-24-09-50-22](https://github.com/user-attachments/assets/b7643704-1767-4de5-9d3f-13865f495b57)
When i try to upload files, and navigate to correct directory, sometimes the list look like this.

Also, it don't show any further directory.

I'm not sure what's the design goal, but i'm sure it's not this. This usecase is very common (tiled chrome taking full workspace, when files pops up it take half the screen).

**Comment by TheESN** [comment]
Looks like it's the same as #154 but file picker didn't get this fix @jackpot51

**Comment by git-f0x** [comment]
I think this may have been fixed.

**Comment by VandaLHJ** [comment]
Yep, looks like this one got fixed.
