### ISSUE TITLE
Jpeg-xl thumbnail support

### ISSUE THREAD

**Issue by drwankingstein** [pop-os/cosmic-files#315]
cosmic-files doesn't currently support jxl images, it would be nice if it did.

**Comment by iamkartiknayak** [comment]
Try this, it worked for me in Cosmic Files

https://ubuntuhandbook.org/index.php/2024/06/enable-jxl-support-ubuntu/

![screenshot-2024-09-25-22-59-08](https://github.com/user-attachments/assets/b74a050d-43a9-4b5d-bd2b-d327ea4f5c3b)

**Comment by Quackdoc** [comment]
Cosmic just merged external thumbnailer support so this is solved.
