### ISSUE TITLE
Remove most options from the Settings pane

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#321]
Almost all settings are set in the menus now. Remove all settings except "Theme" under "Appearance". More settings may arrive later such as storing session, default starting folder, and mounting drives at boot.

**Comment by jackpot51** [comment]
Set the default for all new tabs/windows:
Grid or List View

Global:
Folders first
Icon sizes
Show item preview

Per folder:
Show hidden
Sort type and direction

**Comment by jackpot51** [comment]
Decided that show hidden and sort type and direction will not be persisted for now.

**Comment by oscardssmith** [comment]
Can this decision be revisited? showing hidden files should probably be the default, or at least a configurable option. As a developer, having a file manager that doesn't show all of the files is just plain broken.
