### ISSUE TITLE
Sidebar MVP

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#326]
* Add "Recents" to the top of the Navbar. Recent can't be removed like Trash.
* Add separators per the design

![image](https://github.com/user-attachments/assets/5cd57bf3-6537-4739-9318-8893372cde7e)

[Design File](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=2847-25477&t=FhDYB7EXyARkip9u-0)

**Comment by jackpot51** [comment]
Recents and separators are now there. network file systems will be added in #202
