### ISSUE TITLE
Context menu from main area/icon gets stuck open when navigating to favorite folders

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-files#328]
Video:

https://github.com/user-attachments/assets/c3d95be0-a0bc-467d-a3a8-932abfe61cea

After navigating to the new folder, clicking in the main area doesn't close it anymore (an Esc still closes it).

Version: 190029a

**Comment by l-const** [comment]
I think this issue also should be closed now: https://github.com/pop-os/cosmic-files/issues/389 ,after the merge of  https://github.com/pop-os/cosmic-files/commit/ca4cdb8 @leviport @jackpot51
