### ISSUE TITLE
cosmic-files dialog MVP

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#335]
- [x] Opens tiled when opened via xdg-portal but should float
- [ ] Title has usefulness and is defined by the requesting service. There are responsivenesss issues though and the title should be removed in single-column view.
- [x] Include buttons in header 
  - [x] Search
  - [x] New folder (Do not include for open dialogs)
  - [x] Grid/list selector
  - [x] Sort selector
- [x] Navbar: include the same directories and files as those added/removed by user.
- [x] Navbar: No Recents or Trash
- [x] Navbar: Include additional drives/locations
- [x] Navbar: Separators
- [x] Add choices and filter per design
- [x] Line under the back/forward breadcrumb section
- [x] Responsive to a single column per design
- [x] Order by last modified by default (Do not list directories first)

Previews isn't included here but we'll want them for alpha 2. Design is ready now.

[Design file](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=2301-33940&node-type=CANVAS&t=CEjuXnv18yCF5EBq-0).

**Comment by jackpot51** [comment]
>  Opens tiled when opened via xdg-portal but should float

This needs a floating window exception for `com.system76.CosmicFilesDialog` (cc @Drakulix)

**Comment by jackpot51** [comment]
>  Navbar: Separators

We need support for this in libcosmic. I will work on this if I get to it before @mmstick returns.

**Comment by jackpot51** [comment]
>  Add choices and filter per design

Filters and choices are there, and are close but not exactly like the design. They only appear if the application requests them.

**Comment by jackpot51** [comment]
>  Include Search, New Folder, and Grid/List selector in header (Do not include "New Folder" icon for open dialogs)

I am breaking these into sub-tasks in the list as they will be implemented separately.

**Comment by jackpot51** [comment]
https://github.com/pop-os/cosmic-files/pull/444 probably fixed the line under breadcrumbs.

**Comment by jackpot51** [comment]
Search implemented in 36d61d574d3156234879e337eb0381a796b56119

**Comment by git-f0x** [comment]
Sorry for commenting here, but wasn't sure where else: the color of NavBar separators is a bit too strong, they should have a softer gray color (instead of white/black).

**Comment by jackpot51** [comment]
Sort selector implemented in b851f3dd66a05ddc2d76da603e15b680a18c9bfb

**Comment by jackpot51** [comment]
@git-f0x I will look into it.

**Comment by jackpot51** [comment]
All parts of this are fixed except potentially the window title item. I believe a new issue should be created if that is still a problem. I currently see the window title text being partially hidden as it loses space, which makes sense to me. It will look better when we implement ellipses.

**Comment by QmwJlHuSg9pa** [comment]
Nice progress! Though I'm not liking the location of the "Add Network Drive" dialogue.

I'm pecking around in the sidebar, looking for the "Networks" option, then a dialogue appears from the _other_ side of the screen -- this is where you've lost me. It's an increased mental load on an already mentally-distracting task of hunt-and-pecking. Please consider an option that relocates this nearer to the actual "Networks" option. E.g. tooltip or modal style, etc. Either would be less distracting than having to whip my head from one extremity of the screen to the other.

**Comment by git-f0x** [comment]
The "Add Network Drive" button is on the same side as the sidebar it opens when clicked (on the right).
Putting the dialogue in a modal or similar would require more mouse movement.
The Networks option on the left sidebar doesn't open the "Add Network Drive" dialogue, so not sure what you're referring to.

**Comment by QmwJlHuSg9pa** [comment]
> The "Add Network Drive" button is on the same side as the sidebar it opens when clicked (on the right). Putting the dialogue in a modal or similar would require more mouse movement. The Networks option on the left sidebar doesn't open the "Add Network Drive" dialogue, so not sure what you're referring to.

Fair, I honestly didn't notice that button in the mockup; I had assumed one might access the dialogue by right-clicking "Networks" directly (at least, this is how I would intuitively attempt to add a new network drive). Though it suffers from a similar issue to what I already described -- it's on the opposite side of the screen to the "Networks" button.
