### ISSUE TITLE
Search results > Include location under the file name (or someplace else)

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#338]

**Comment by maria-komarova** [comment]
![Search results](https://github.com/user-attachments/assets/719b8e46-f033-45c7-a3e2-615fbc0e4961)
[Figma mockups](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=3994-36040&t=kIEFDDY8qdfE2tMj-4).
