### ISSUE TITLE
NavBar entry isn't highlighted on startup

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-files#344]
The Home NavBar entry isn't highlighted when cosmic-files is opened. It becomes highlighted when clicked or when going to another folder and back to home.
Edit: It also doesn't change highlights when switching tabs.

Probably unrelated, but right clicking on a NavBar entry to open the context menu makes that entry persistently highlighted, even after the context menu is closed.

**Comment by iamkartiknayak** [comment]
I was about to post this issue. It's been more than 3 weeks I've posted this issue in X(Twitter) tagging the official account and they never responded back. I guess GitHub issue will be noticed
