### ISSUE TITLE
Feature request - Fractional scaling toggle or DPI consideration

### ISSUE THREAD

**Issue by shadywack** [pop-os/cosmic-files#345]
This may be a somewhat complicated task, but the ask is to help mitigate xwayland based apps with their blurry behavior when enabling fractional scaling.

This is a well understood and documented issue for Gnome users, and some of Cosmic's reliance on gtk apps exposes some of the issue given that it's Wayland native. Plasma works around this issue somewhat with the option to allow apps to scale themselves, which does indeed result in xwayland apps behaving under the Plasma compositor.

Is there a plausible path forward for Cosmic to pursue this type of behavior, or at least port over Gnome's forthcoming mutter solutions as those are developed?

An alternative would be to have an option to disable fractional scaling in the meantime, which would at least allow users to pick 200% - 300% scaling to get xwayland apps to look crisp.

Congrats on the launch of the alpha, and thank you S76 for the fantastic work on such a clean, pleasant DE. I appreciate consideration for this request

**Comment by WatchMkr** [comment]
This is under development in cosmic-comp.
