### ISSUE TITLE
[ENHANCEMENT] Auto Select Filename When Renaming in Cosmic Files

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-files#367]
## Description:
When renaming a file or directory in Cosmic Files, the filename should be automatically selected, excluding the extension. This would streamline the renaming process, as users often need to change only the name and not the extension.

## Proposed Feature:

- Automatic Selection: When a file or directory is subjected to renaming, the entire filename (excluding the extension) should be selected by default.
- User Experience: This would simplify the renaming process, reducing the need for manual selection and minimizing errors when changing file names.

**Comment by Airradda** [comment]
This seems to be a duplicate of #181, unless I am mistaken.

**Comment by iamkartiknayak** [comment]
Thank you for pointing out the duplication. I'll close this issue and track progress on the original issue at #181
