### ISSUE TITLE
Feature request: more keyboard bindings

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-files#38]
- [x] Delete key should move selected file to the trash
- [x] Arrow keys should change selected file
- [x] Enter key should open selected file
- [x] Ctrl + L should focus the current path box so I can type a different location
- [x] Ctrl + Shift + N should create a new directory
- [ ] Ctrl + Z should undo
- [x] Esc should close the right hand drawer thing

**Comment by leviport** [comment]
Also, for the File > Open dialog, I think Esc should probably close the dialog, same as clicking the "cancel" button

**Comment by joshuamegnauth54** [comment]
This is a great list. I attempted the "arrow key movement" and "enter to open" keys a few weeks ago, but I couldn't figure them out. They're surprisingly non-trivial. I attempted them again today but still failed.

On the bright side, I opened a PR for the last request.

**Comment by jackpot51** [comment]
This is mostly implemented as of 6e14a0b but I'll need to rework the grid to make the arrow keys do the right thing there.

**Comment by jackpot51** [comment]
Everything but Ctrl+Z is implemented properly now. I'm closing as I'd like to handle undo with a new issue.
