### ISSUE TITLE
[Suggestion] Do not hide files behind file "details" panel

### ISSUE THREAD

**Issue by peterkrull** [pop-os/cosmic-files#387]
I quite like the space-bar to preview files feature in Nautilus (Gnome files). And it is *almost* present in cosmic for certain files, but it is a problem that it is covering up the directory contents. In Nautilus this is not an issue since the preview opens in a separate window. The details panel does not feel like an integrated part of the interface because of this.

https://github.com/user-attachments/assets/625a5d22-9f74-42e9-8b27-d7782cb7dcdc

I would suggest to shrink the left side of the container showing the directory contents whenever the details panel is open.

**Comment by peterkrull** [comment]
Seems like this suggestion may already be planned behavior for all context drawers, according to [the designs](https://www.figma.com/design/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=12300-54758&t=9ifkCc9bHGnHFWrg-0)

**Comment by WatchMkr** [comment]
We're tracking this here: https://github.com/pop-os/cosmic-files/issues/109
