### ISSUE TITLE
Right-click context menu persists after changing directory

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-files#389]
Right clicking brings up the context menu. If you then click on a directory in the sidebar, the context menu stays visible or sometimes "hides" but is actually still there.
Attached video (obs did not capture my mouse).

https://github.com/user-attachments/assets/0b58a5ac-97a9-40c2-be7b-4cf19e7a2dd2

cosmic-files: 0.1.0~1723730056~22.04~bd233d8

**Comment by jackpot51** [comment]
I believe this is fixed
