### ISSUE TITLE
No fast way to close "Complete" notification in right side drawer thing

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-files#39]
When I delete a file, the right hand drawer opens with the notification that the operation has been completed. This makes the rest of the file browser insensitive, so I have to close it before I can continue with whatever I was doing. Clicking files does not close it, and it blocks my click. Hitting Esc also does not close it, so I have to use my mouse.

**Comment by maria-komarova** [comment]
I don't see that happening now so maybe not relevant anymore?

**Comment by leviport** [comment]
I also don't see the Operations pop-over appear anymore. I'm not sure if that's a whole new bug though. Should it be appearing?

Also, if I open the Operations drawer with Edit > Operations, I can now close it with Esc, but I think clicking back on the parent window should probably close it also. If it's supposed to, I can open a bug report.

**Comment by maria-komarova** [comment]
Context drawer is generally only closed by clicking on Close now. We can think about closing it on clicking outside in certain cases but it is not a menu.
I'm not sure about Operations context drawer. Was it appearing when you Deleted an item before? I don't think that should be the case.
