### ISSUE TITLE
[Feature Request] Add "Create New Folder" to file open prompt.

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-files#391]
When opening Calibre ebook application, it will ask where you would like to store your ebook library. If you do not like the default, you can choose which directory to store files. When the file open prompt pops up, there is no option to "Create New Folder". It is possible to right click and create a new folder from the context menu, but a visible "Create New Folder" button would be helpful.

cosmic-files: 0.1.0~1723730056~22.04~bd233d8

**Comment by WatchMkr** [comment]
Tracking this here: https://github.com/pop-os/cosmic-files/issues/335

**Comment by amozeo** [comment]
This is still an issue, there is no way to create directory from the "Open flie" dialog (or I am blind and can't find a way).
I understand that not putting a dedicated button for it is a design decision, but then it should be in the three dots menu instead.

*cosmic-files revision: 2ba08c4928271959d07526856b28385cf9b04646*
