### ISSUE TITLE
[Feature request] Show system root folder

### ISSUE THREAD

**Issue by hfc2x** [pop-os/cosmic-files#395]
I know most people would probably not want this, but it would be useful to have an option to add `/` to the side panel. As it is, it's not possible to do that (or I couldn't find a way). The only way to do this currently is by either editing the top bar to manually go to `/`, or by using the terminal.

Having a toggle in the COSMIC Files settings to show the system root could be very useful. Maybe having a setting that's off by default will be better, since most people will probably not need to see it.

**Comment by matte-schwartz** [comment]
+1 to this, would be great for development work where I need to access different root filesystem folders and pinning them individually to the sidebar gets a bit overwhelming.

**Comment by Department-stack** [comment]
+1 I use this feature on dolphin often

**Comment by Department-stack** [comment]
It would be better to be able to "pin" whatever you want to the side panel instead of this specific option in my opinion

**Comment by Karvie0** [comment]
> It would be better to be able to "pin" whatever you want to the side panel instead of this specific option in my opinion

There already is an option to add folders to the sidebar. The problem is that you need to right click on the folder to do so, and you cant do that with `/` because you're in the folder. This also means that you can't open the properties menu for `/`, but that's less of an issue

**Comment by Department-stack** [comment]
Thank you for the knowledge, didn't know you could do that! I also hope that your feature request gets added

**Comment by soccerboys2008** [comment]
i found a workaround, but still would be better to have it there officially

1. open terminal and create a link to root (somewhere) `ln -s / root`
2. navigate to where you made the link, then right click it , then add to sidebar

honestly i would like to see this go a little further then just having root in the sidebar, maybe more like the "Other Locations" option from nautilus (which includes root) or similar

**Comment by WatchMkr** [comment]
Plan is to add the "Add to sidebar" option to the breadcrumb context menu.
![image](https://github.com/user-attachments/assets/4537314a-f734-403a-92d1-86ed76682539)
