### ISSUE TITLE
[Feature request] Open in terminal

### ISSUE THREAD

**Issue by hfc2x** [pop-os/cosmic-files#396]
What's in the title, pretty much. Most file browsers tend to include a right-click option to open the current directory in the terminal.

**Comment by l-const** [comment]
Hey @hfc2x ,  i think this is supported already : 
![screenshot-2024-08-16-11-24-11](https://github.com/user-attachments/assets/01eb86f4-bb57-4259-a6d4-75bf7828f5fe)

**Comment by SoloRobo** [comment]
Coming back to this (if I can?)

Could you add "Open in Terminal" in the following locations:

Right clicking the folder in the bar at the top
![Image](https://github.com/user-attachments/assets/0f4ce09b-a500-4588-8e11-6ab3a3c26dc2)

Right clicking a file - but it opens it's parent folder
![Image](https://github.com/user-attachments/assets/a2b4e5e5-9c66-4772-aca0-9a69c91b9f6f)
