### ISSUE TITLE
feature request : Show drives and usb on the right hand side of the file manger

### ISSUE THREAD

**Issue by ryzendew** [pop-os/cosmic-files#40]
![homematt — COSMIC File Manager_2024-02-13_171740_2495](https://github.com/pop-os/cosmic-files/assets/84041391/99d64f50-ceae-4584-a3d3-224a51e21451) Cosmic file manager
So normally on gnome file manager drives will show on the right hand side and i would like that on cosmic also 

![Home_2024-02-13_171922_5264](https://github.com/pop-os/cosmic-files/assets/84041391/c7e5b971-8710-4dda-b897-526254731113) Gnome File manager

**Comment by jackpot51** [comment]
This was implemented with the gvfs feature
