### ISSUE TITLE
Context menu is not closed when navigating to different folders but this is not consistent as well.

### ISSUE THREAD

**Issue by l-const** [pop-os/cosmic-files#404]
Please see the recording for more: 
Cosmic files version: https://github.com/pop-os/cosmic-files/commit/bd233d8

https://github.com/user-attachments/assets/61dc08fd-33d2-4955-bdb2-263e38f1f7b2

**Comment by leviport** [comment]
Duplicate of https://github.com/pop-os/cosmic-files/issues/389
