### ISSUE TITLE
feature request: image and video tumbnails that just work

### ISSUE THREAD

**Issue by nonetrix** [pop-os/cosmic-files#41]
A thing about most graphical file managers that annoys me to no end on Linux is that they don't support thumbnails well enough, most of the time images are fine, but videos I have never been able to get working in a single graphical file manager. And in some extreme cases images aren't even present. It's so bad that I can get more graphical features in my terminal file manager and it mostly just works, see image below for a example of a video thumbnail
![image](https://github.com/pop-os/cosmic-files/assets/45698918/62474e6f-d2e9-46c0-b106-fd90fcffac43)

**Comment by Quackdoc** [comment]
video thumbnails may want to rely on a separate library/crate, I'm not sure of any current rust libraries for handling them, but you need to first check the container for an embedded thumbnail, and if one doesn't exist, generate one yourself. much like the [ffmpegthumbs](https://invent.kde.org/multimedia/ffmpegthumbs) library or [ffmpeg thumbnailer](https://github.com/dirkvdb/ffmpegthumbnailer)

image thumbnails are easier to generate using image-rs for the majority of them (though it does lack support for jxl and likely wont get support for a while)

**Comment by mmstick** [comment]
We could call ffmpeg commands in the background to generate video thumbnails.

```
ffmpeg -ss 100 -i input.mp4 -vf "select=gt(scene\,0.5),scale=320:-1" -frames:v 1 -vsync vfr output.jpg
```

Which skips the first 100 seconds of the video and looks for the first scene with a 50% difference.

**Comment by mmstick** [comment]
It takes about a half second or two to generate a frame, and you could alternatively use the `thumbnail=n=1000` video filter to limit the search within 1000 frames to make it even faster. The `ss` argument above seeks through first 90 seconds of frames without decoding, so it is relatively instantaneous.

We already use tokio for spawning processes asynchronously on a tokio runtime running in the background, so spawning a couple ffmpeg processes and asynchronously updating the UI is easy.

**Comment by jackpot51** [comment]
External thumbnailing is now supported using entries in /usr/share/thumbnailers

**Comment by nonetrix** [comment]
Maybe dumb question, but does this work in file picker too? I assume you write a script? How exactly does that work? Maybe PopOS should ship ones for video
