### ISSUE TITLE
[Feature Request] "Copy path"

### ISSUE THREAD

**Issue by Elias-Graf** [pop-os/cosmic-files#410]
The context menu should feature a "Copy path" item.
![image](https://github.com/user-attachments/assets/8907b00e-74ab-423f-a05b-360bc527cae8)

**Comment by francesco-gaglione** [comment]
@Elias-Graf  currently if you copy the path will be copied so copy path is useless. Or do you mean something different with capy path?

**Comment by Elias-Graf** [comment]
Yup, didn't even consider that would be the case, I assumed there would be some "file explorer specific" format. Being used to windows, I assumed there was a need for a specific option.

(The only benefit for still adding the option, would be that it's easy to discover / more accessible for people that don't know, like me, that just the path is copied anyway. But that's probably not a focus right now.)
