### ISSUE TITLE
Search bar retains focus after clicking file (breaks copy)

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-files#413]
Version: b6bc513

Steps to recreate:
1. Search for a folder
2. Double-click to enter the folder
    - The text remains in the search bar, but the main view is no longer search results.
3. Click a file, press Ctrl-C, then press Ctrl-V to try and duplicate it.

Expected result: File is duplicated.

Actual result: The file was not copied when pressing Ctrl-C, and whatever was in the clipboard before gets pasted into the search bar when pressing Ctrl-V (even though I'm no longer trying to interact with the search bar).

Other notes: If we make the search bar lose its focus when a file is selected (and make it need a click or Ctrl-F to get focus back), that seems like it'd be an easy way to fix the issue.

**Comment by jackpot51** [comment]
This appears to be fixed after the search redesign
