### ISSUE TITLE
[Bug] Sidebar not populated in "Open Folder" mode

### ISSUE THREAD

**Issue by Elias-Graf** [pop-os/cosmic-files#416]
![image](https://github.com/user-attachments/assets/ee83edb3-9ca6-4b88-ab11-e6d5fb27dc94)

Version: aebc65200685517fff0785cf17636d92218d7ba6 (btw. a `cosmic-files --version` would be nice, currently it just opens the GUI).
OS: NixOS 24.11.20240814.c3aa7b8 (Vicuna) x86_64

**Comment by WatchMkr** [comment]
tracking here: https://github.com/pop-os/cosmic-files/issues/335
