### ISSUE TITLE
bug report — double clicking search input field changes window size

### ISSUE THREAD

**Issue by BBBalls** [pop-os/cosmic-files#443]
**Cosmic-files version:**

0.1.0~1725629103~22.04~3626097

**Issue/Bug description:**

Double clicking the search input field changes the widow size of cosmic-files.

**Steps to reproduce:**

Double click the search input field of cosmic-files.

**Expected behavior:**

The window to not change size double clicking the search input field.

**Other notes:**

Discovered this bug doing a series of searches with cosmic-files. I double clicked the search input field to select all of the text in the search input field.

**Comment by WatchMkr** [comment]
We're tracking this here: https://github.com/pop-os/libcosmic/issues/567
