### ISSUE TITLE
Icons have slight background

### ISSUE THREAD

**Issue by A-Walrus** [pop-os/cosmic-files#46]
Icons have a very faint, but still visible background.

Not sure if specific to `cosmic-files` or just generally all `cosmic` apps

**Full image**
![screenshot-2024-02-17-14-52-03](https://github.com/pop-os/cosmic-files/assets/58790821/f5004d4c-ad08-4bcc-a170-9eb4e2acfa44)

**Cropped to zoom in on icon**
![screenshot-2024-02-17-14-52-03-c](https://github.com/pop-os/cosmic-files/assets/58790821/ff98668f-0976-4d76-9108-57ba80fe8921)

**Comment by git-f0x** [comment]
This should be fixed.
