### ISSUE TITLE
[Bug]: Zooming via Ctrl + Mouse Scroll Doesn't Update Icon Size Slider

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-files#469]
**Cosmic-files version:**
```
cosmic-files:
  Installed: 0.1.0~1726594874~22.04~0fe302a
  Candidate: 0.1.0~1726594874~22.04~0fe302a
```

**Issue/Bug description:**
When zooming in or out in Cosmic Files using Ctrl + mouse scroll, the icon size changes as expected, but the icon size slider in the Cosmic Files settings UI does not reflect these changes. The slider remains in its previous position, creating a mismatch between the actual icon size and the UI's representation of it.

**Steps to reproduce:**
-> Open Cosmic Files
-> Modify zoom level with `ctrl` + `mouse scroll`
-> Verify the bug in Cosmic Files settings using `ctrl` + `,`

**Expected behavior:**
To update the icon size slider when zoomed in and out using `ctrl` + `mouse scroll`

**Other notes:**

https://github.com/user-attachments/assets/4345437a-819c-4fe0-b019-115895ec6604

**Comment by l-const** [comment]
Hey @iamkartiknayak , this is the same with `Ctrl + =` and is the intented behaviour as zoom_adjustment is intented to not be persisted across sessions like icon size or font size change in cosmic-term.

**Comment by iamkartiknayak** [comment]
But the slider value should update regardless whether the values persist across sessions or not

**Comment by l-const** [comment]
The default font size doesn't change as well when you zoom  in cosmic-term, so what I am implying is that those are implemented to be two different specific things/variables,  so zooming in should not update the icon size that is actually persisted in the filesystem config folder.

**Comment by iamkartiknayak** [comment]
Thanks for clearing things up. I'll close it as this was not a bug
