### ISSUE TITLE
[Bug]: Changing ListView Icon Size switches the current view to GridView in Cosmic Files

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-files#470]
**Cosmic-files version:**
```
cosmic-files:
  Installed: 0.1.0~1726594874~22.04~0fe302a
  Candidate: 0.1.0~1726594874~22.04~0fe302a
```

**Issue/Bug description:**
 When adjusting the ListView or GridView icon size Cosmic Files Settings, the view unexpectedly switches from ListView to GridView if GridView is default or vice versa.

**Steps to reproduce:**
-> Open Cosmic Files
-> Modify `Icon size(list)` slider value if GridView is default or vice versa
-> Verify the bug by seeing the change in current selected view

**Expected behavior:**
The expected behavior is for the icon size to change within current view itself, without altering the view mode

**Other notes:**

https://github.com/user-attachments/assets/521e795c-a557-4e65-9371-83fc1bdacabe

**Comment by WatchMkr** [comment]
Icon size options will be removed from the Settings page now that they're in the View menu. Zoom is working correctly from the menu.
