### ISSUE TITLE
[FEATURE]: Request for Thumbnail Support for HEIC, SVG and other Video Formats

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-files#471]
**Cosmic-files version:**
```
cosmic-files:
  Installed: 0.1.0~1726594874~22.04~0fe302a
  Candidate: 0.1.0~1726594874~22.04~0fe302a
```

**Issue/Bug description:**
HEIC, SVG and other video files such as (.mp4, .mkv, .mov). Currently, Cosmic Files does not generate thumbnails for these file types, which impacts the ability to quickly preview them within the application.

**Steps to reproduce:**
N/A

**Expected behavior:**
Cosmic Files should generate a small thumbnail preview of the image, vector or video file

**Other notes:**
![screenshot-2024-09-17-21-12-41](https://github.com/user-attachments/assets/f7dddb32-dfad-41cd-8adb-4418e7df42e4)

Similar issue mentioned here #315

**Comment by jackpot51** [comment]
External thumbnailing is now supported using entries in /usr/share/thumbnailers
