### ISSUE TITLE
[FEATURE REQUEST]: Add "Safely Remove Drive" Option for External Storage Devices in Cosmic Files

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-files#479]
**Cosmic-files version:**
```
cosmic-files:
  Installed: 0.1.0~1726676662~22.04~8668c18
  Candidate: 0.1.0~1726676662~22.04~8668c18
```

**Issue/Bug description:**
Currently, users may not have a clear or reliable method to safely unmount external storage devices. Providing this option would enhance user experience and ensure data integrity when disconnecting drives. Current implementation just unmounts the drive.

**Steps to reproduce:**
N/A

**Expected behavior:**
- Eject button for unmounting the drive
- `Safely Remove Drive` context menu for ejecting effectively removing the entry from sidebar. 
- Notification for just ejecting the device.
- Internally connected device such as HDD should only have  unmount button.
- Devices connected via USB whether Pendrive or HDD should have option to "Safely Remove Drive"

**Other notes:**

https://github.com/user-attachments/assets/161c8750-6471-42b5-8bf0-31af1c69dcf1

**Comment by jackpot51** [comment]
The eject button should be fixed so it is doing this, and a toast should be shown when done.
