### ISSUE TITLE
[FEATURE REQUEST]: Toggle Button to Enable/Disable Quick Preview on Item Selection in Cosmic Files

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-files#483]
**Cosmic-files version:**
```
cosmic-files:
  Installed: 0.1.0~1726882610~22.04~73ed4cf
  Candidate: 0.1.0~1726882610~22.04~73ed4cf
```

**Issue/Bug description:**
Feature that adds a toggle button in Cosmic Files settings to enable or disable quick preview when selecting items (such as images, videos, documents, etc.) which was introduced in #109. This would allow users to control whether the preview pane automatically displays file content upon selection, giving more flexibility to workflows where quick preview may not be desired.

**Steps to reproduce:**
N/A

**Expected behavior:**
- When the toggle for Quick Preview is enabled in the settings, Upon selecting a file (e.g., image, video, document), a preview of the file is displayed immediately in the preview pane.
- When the toggle for Quick Preview is disabled in the settings, Upon selecting a file, preview pane wont pop up automatically allowing users to to navigate without closing preview pane each time they select a file.

**Other notes:**

https://github.com/user-attachments/assets/b8395a16-ed64-4721-ae0c-61d194bce124

**Comment by senntore** [comment]
I would like this as well. I liked the previous behavior, where I could choose when to see the previews using space bar.
It is still possible but the automatic previews always seem to happen on first selection after the last update.

**Comment by Minc3** [comment]
The default should be disabled.

**Comment by soccerboys2008** [comment]
> I would like this as well. I liked the previous behavior, where I could choose when to see the previews using space bar. It is still possible but the automatic previews always seem to happen on first selection after the last update.

same even though i used the context menu for it, just learned the spacebar could be used as a keyboard shortcut

**Comment by WatchMkr** [comment]
Completed here: https://github.com/pop-os/cosmic-files/issues/540
