### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#5]
**File**
New tab Ctrl + T
New window Ctrl + N
New folder Ctrl + Shift + N
Close tab Ctrl + W
-- separator --
Open Enter
Add to favorites Ctrl + D
-- separator --
Quit Ctrl + Q

**Edit**
Undo Ctrl + Z
Redo Ctrl + Shift + Z
-- separator --
Cut Ctrl + X
Copy Ctrl + C
Paste Ctrl + V
Select all Ctrl + A
-- separator --
Find Ctrl + F
Advanced find Ctrl + H

**View**
Zoom in Ctrl + =
Default size Ctrl + 0
Zoom out Ctrl + -
-- separator --
List view [radio button]
Grid view [radio button]
-- separator --
[checkbox] Show file preview
[checkbox] Show hidden files
[checkbox] List directories first
-- separator --
Settings

**Comment by jackpot51** [comment]
I'd recommend to put Close tab in its own section. It was done for cosmic-term and cosmic-edit

**Comment by jackpot51** [comment]
Partially implemented in 1aba09a
