### ISSUE TITLE
[Feature Request] keep file selected as its updated or overwritten

### ISSUE THREAD

**Issue by soccerboys2008** [pop-os/cosmic-files#506]
sometimes a file could be updated or overwritten multiple times a second (depending on whats happening), in these cases it could be hard to open the file (like in a browser to see a snapshot of what it looked like), or to something in the right click menu with a file changing so much

**Cosmic-files version:**
0.1.0~1724947923~22.04~d923efa

**Issue/Bug description:**

**Steps to reproduce:**

**Expected behavior:**

**Other notes:**
video as example:
https://drive.google.com/file/d/1mPnKD424lg4Oeb815qAvsuVNsQ41XI3m/view?usp=sharing

**Comment by jackpot51** [comment]
This should have been fixed by https://github.com/pop-os/cosmic-files/commit/03b6b6bb45a167ea5bb30335986f3a18c015562b

**Comment by soccerboys2008** [comment]
it has been a minute since i updated cosmic files (current version installed is above. ill update it and see if there is a change (as long as its available through apt, since the change was added yesterday)

**Comment by jackpot51** [comment]
Can you close this if it is fixed?
