### ISSUE TITLE
[BUG] Accent color in Cosmic Files does not change in real-time in light mode

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-files#516]
**Cosmic-files version:**
```
cosmic-files:
  Installed: 0.1.0~1727456658~24.04~5e0ef57
```

**Issue/Bug description:**
When changing accent color in Settings, Cosmic Files accent color does not update in real-time when the system is in light mode. The color change only takes effect if the system is switched to dark mode and then back to light mode again. This issue occurs consistently when attempting to change the accent color while staying in light mode.

**Steps to reproduce:**

https://github.com/user-attachments/assets/a6c594ce-1171-4c8b-87b6-b0dc363a2faa

**Expected behavior:**
The accent color should update in real-time in Cosmic Files when it is changed in the system settings, regardless of the current mode (light or dark).

**Other notes:**

**Comment by git-f0x** [comment]
Likely the same issue as pop-os/cosmic-epoch#915.
