### ISSUE TITLE
feature request : applications folder

### ISSUE THREAD

**Issue by tdeffieux** [pop-os/cosmic-files#52]
Would be nice to have an Applications folder view to be able to install/launch/clean/remove/inspect apps visually for flatpacks apps.
The file manager would handle the view and call the different commands behind the scene and would also support drag and drop from pop_shop.
Each app would be launched directly by clicking on it but could also be opened as a virtual folder with symlinks to the ~/.var/app config directory, to its binaries directory and to the .desktop file for manual edits.
Obviously that needs more refined thoughts !

An example of a deamon that monitors an Application folder
https://github.com/axtloss/mac-style-flatpak

**Comment by jackpot51** [comment]
We won't be working on this
