### ISSUE TITLE
[bug] Double-clicking an executable doesn't launch it

### ISSUE THREAD

**Issue by alphabitserial** [pop-os/cosmic-files#525]
**Cosmic-files version:** 1.0.0.alpha.2.r20.g8dd26b6-1

**Issue/Bug description:** When double-clicking an executable file, it tries to open in another application (in my case Firefox) instead of launching the executable

**Expected behavior:** If an ELF or script is already marked as executable, it should launch on double-click. If not, it should prompt the user to confirm their intent to launch it.

**Other notes:** See KDE's Dolphin file manager for an example of the expected behavior

**Comment by git-f0x** [comment]
Duplicate of #23.

**Comment by alphabitserial** [comment]
Thanks, will close this & follow that.
