### ISSUE TITLE
Dialog Mode Preview Design Improvements

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#541]
- [x] Show details open by default
- [x] Button or checkbox to disable/enable (no View menu and considering that the "Close" button also disables)
- [x] Design show details empty state
- [x] Move buttons and option details in to the footer (so they don't move when show details is open/closed and are visible in single column)

**Comment by iamkartiknayak** [comment]
Moving the navigation button to bottom would be great. 
Gallery view can be updated in future with more options in bottom like 
- Rotate left & right
- Slideshow 
- Add to favorites ...etc

**Comment by iamkartiknayak** [comment]
Also showing a button to enable a row at the bottom of these options displaying available images in smaller previews to scroll through and select between different index would be awesome.
