### ISSUE TITLE
Search Design Improvement

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#550]
- [x] Do not modify the breadcrumb trail when searching (no search glass or search term - these are represented by the search box)
- [x] The search box is specific to the tab. A different tab can have a different search term or be closed. This is so that it's clear the items shown are a result of the search query or lack thereof.
- [x] In single column, the search bar drops to a second line

[Figma design file](https://www.figma.com/design/ZBg577prx1KF8BlZrBSgT0/Files?node-id=3994-36040&t=Ix0WlzbeKKvj49Et-4)

**Comment by jackpot51** [comment]
Opening for single column design.
