### ISSUE TITLE
Desktop mode > Panels can cover "undo" toast

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-files#560]
![image](https://github.com/user-attachments/assets/cfff0424-79d0-40e1-8239-29b0c5b7895e)

**Comment by jackpot51** [comment]
We need some way to dodge panels, they can overlay any contents.

**Comment by WatchMkr** [comment]
Can we position the top and bottom of the cosmic-files overlay outside the largest panel size?

**Comment by jackpot51** [comment]
Yes, we can

**Comment by jackpot51** [comment]
The largest panel size is pretty big, though

**Comment by git-f0x** [comment]
There's also left and right, so it's probably better to just reserve the space used by panels (if possible).
