### ISSUE TITLE
bug(desktop): context menu does not close when clicking off the menu with no files in Desktop folder

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-files#563]
**Cosmic-files version:**

cosmic-files-1.0.0~alpha.2^git20241003.d3f91e6-1.fc40.x86_64

**Issue/Bug description:**

when clicking off the right click context menu on the desktop, the context menu stays. The context menu should also likely go away when switching workspaces, but I don't know how cosmic-files could hook into the interface to determine that.

**Steps to reproduce:**

remove any files from the $HOME/Desktop folder

right click on the desktop

left click anywhere else on the desktop

the context menu won't go away

**Expected behavior:**

the context menu goes away

**Other notes:**

https://github.com/user-attachments/assets/6b8f73fd-21b0-4fe3-b734-b65c13bf9a84

**Comment by iamkartiknayak** [comment]
Duplicate of #493

**Comment by ryanabx** [comment]
Closed, duplicate
