### ISSUE TITLE
[Accessiblity] Allow some cursor motion during double click

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-files#575]
**Cosmic-files version:**
`0.1.0~1728135543~24.04~e997bbb`

**Issue/Bug description:**
The cursor moving even a single pixel between the clicks of the double click resets the counter, which results in a file/folder not opening and the app feeling unresponsive.

**Steps to reproduce:**
Double click a file/folder, but slightly move the cursor between clicks (accidentally or deliberately).

**Expected behavior:**
Other file managers allow some motion between clicks, and this would improve accessibility.

**Other notes:**
The double click text selection in e.g. `cosmic-edit` seems to allow some motion, so this issue might be specific to Files, rather than a libcosmic/iced issue (though it might be specific to the libcosmic widget that files/folders use).

**Comment by l-const** [comment]
Yeah, it would be great if we could somehow address this issue.

**Comment by l-const** [comment]
I did some search on what gtk/libadwaita/mutter does and it seems that gtk defines a double_click_distance, you can see some code search results here: https://github.com/search?q=org%3AGNOME+double_click_distance&type=code , so i assume libcosmic may need to define something like this for the mouse_area.rs widget, I've seen many other even youtubers facing this issue and some people might mistake this is a perf issue. In my humble opinion this is probably prioritised.

**Comment by l-const** [comment]
I guess it it a gtksetting? 
 ```
 i guess it is a gtksetting?  /**
   * GtkSettings:gtk-double-click-distance:
   *
   * The maximum distance allowed between two clicks for them to be considered
   * a double click, in pixels.
   */
  pspecs[PROP_DOUBLE_CLICK_DISTANCE] = g_param_spec_int ("gtk-double-click-distance", NULL, NULL,
                                                         0, G_MAXINT, 5,
                                                         GTK_PARAM_READWRITE);

```

**Comment by l-const** [comment]
I think that those toolkits do not see any regressions although  they define it in a global way because it is really difficult to want to intentionally click on a sibling Element and move only < 5 pixels and also manage to do that within the already defined DOUBLE_CLICK_TIMEOUT = 500ms, so i do not think there is going to be any regressions. This issue is observed when you know you want to traverse a file path quickly and you move the mouse really quickly so your second click is sometimes off by a few pixels.
