### ISSUE TITLE
Fullscreening applications freezes PC

### ISSUE THREAD

**Issue by Padrone0** [pop-os/cosmic-files#583]
I'm using Arch and installed Cosmic through sudo pacman -S cosmic-session

**Issue/Bug description:**
When I fullscreen now either firefox or Freetube (which always opens in fullscreen) the whole pc freezes or atleast what im seeing music still runs in the background.

**Steps to reproduce:**
Fullscreen either firefox or open Freetube
**Expected behavior:**
Pc not freezing
**Other notes:**
This did not happen before alpha 2
Im pretty sure its any application if i fullscreen it but its annoying to test cause i have to force shutdown my pc through power button
I have 3440x1440 resolution

**Comment by jacobgkau** [comment]
The user re-opened the issue here: https://github.com/pop-os/cosmic-epoch/issues/1097
