### ISSUE TITLE
[Feature] Bitlocker support in the file manager

### ISSUE THREAD

**Issue by Zeanix** [pop-os/cosmic-files#596]
It seems that the file manager does not (yet) support bitlocker encryption. Partitions can be unlocked from the disks application and then used in the file manager, but being able to unlock them directly from the file manager would be preferable.

**Comment by jackpot51** [comment]
Please try this again, I believe it was fixed by 583d3dfa0d0c5a0132f457968ea4383835118f25

**Comment by Zeanix** [comment]
Yes, it works now. My disks can be unencrypted in the file manager.
