### ISSUE TITLE
Issues with the settings panel

### ISSUE THREAD

**Issue by Koranir** [pop-os/cosmic-files#60]
- The text is wrapped way too early
![image](https://github.com/pop-os/cosmic-files/assets/101683475/0c372c33-2eed-4701-9b87-de53c8fd1831)
- When the settings panel is open, all interaction to the central files panel do nothing, not even closing the settings panel (clicking on an item in the favourites will switch to its directory, but not close the settings either).

**Comment by Quackdoc** [comment]
for the first issue, It would be nice if the text were to stack on top of the interactive bars. I personally tried this with a "mobile size" display and it worked more or less fine when trying to emulate a phone aspect ratio, but some slimmer phone aspect ratios did similar behavior

**Comment by jackpot51** [comment]
This is fixed now.
