### ISSUE TITLE
[BUG] Memory leak with desktop files applet

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-files#613]
**Cosmic-files version:**
Git Commit: d29baf1a8fdc7572df31574b7a1d0ac2db888a2c

**Issue/Bug description:**
Making use of the COSMIC desktop file icons continuously raises memory usage the longer they remain open, eventually filling up all your systems memory.

**Steps to reproduce:**
Right now it's completely unclear to me what's caused it, it seems like after using COSMIC for long enough something goes wrong in the applet and memory usage suddenly spikes upwards of 70GB. 

My current hypothesis is it's related to VRAM usage, as this seems to continue climbing the longer COSMIC runs, which presumably eventually runs out and then overflows into system memory

**Expected behavior:**
No memory leak

**Other notes:**

**Comment by git-f0x** [comment]
I wonder if this might be related to the amdgpu issues on kernel 6.11.
After I updated to Fedora 41 KDE (from 6.10 to 6.11), I had way higher VRAM usage in some games (and thus massive performance issues), so COSMIC might be triggering the same issue as those games.
On Pop COSMIC (6.9.3), VRAM usage is normal, and I haven't encountered/noticed this issue.

**Comment by BrodieRobertson** [comment]
Would there be value in trying to replicate the issue on an LTS kernel

**Comment by git-f0x** [comment]
Maybe. Files was recently rebased to a newer Iced version, so there may be some improvements from that.
But if you have time, it would possibly be useful to know if the issue is still present on 6.11 with the latest Files commits; and if yes, if it's also present on an older kernel.

**Comment by BrodieRobertson** [comment]
COSMIC VRAM usage in general appears to be considerably lower and I'm not seeing anything out the ordinary with RAM, the amounts used also appear to be have stabilized  with this rebase. Currently running kernel 6.11.5
