### ISSUE TITLE
[BUG/UI]: View dropdown context menu  is not visible when in mobile view.

### ISSUE THREAD

**Issue by l-const** [pop-os/cosmic-files#616]
**Cosmic-files version:**

Git version: 3767a61f
**Issue/Bug description:**

**Steps to reproduce:**

**Expected behavior:**

**Other notes:**

![screenshot-2024-10-20-21-09-35](https://github.com/user-attachments/assets/2f83d3b4-f364-4f7d-b7b2-7341452a5b75)

**Comment by git-f0x** [comment]
Likely the same issue as pop-os/libcosmic#258.

**Comment by l-const** [comment]
You mean that this won't be an issue when the menus are collapsed in one, right? I guess this is tracked there, so closing!

**Comment by git-f0x** [comment]
No, it's a different issue where the menus can't be drawn outside the app window. Fixing it seems to currently be planned for Epoch 2.
