### ISSUE TITLE
Incorrect handling of longer filenames

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/cosmic-files#7]
Here is an example of how it incorrectly wraps the filename, it does not improve even if I resize the window either. 

EDIT: Full name in this example:

pop-support_1704729577.tar.xz

![Screenshot from 2024-01-10 06-53-41](https://github.com/pop-os/cosmic-files/assets/4884946/d63fcf1a-4b10-4a0d-a6a8-909d3eff8c3c)

![Screenshot from 2024-01-10 06-53-20](https://github.com/pop-os/cosmic-files/assets/4884946/423e6d7a-f48f-4e6d-85eb-1132414e8961)

**Comment by leb-kuchen** [comment]
![Uploading screenshot-2024-03-27-00-09-29.png…]()
In list view, it will cut off the name if the name is to long.

**Comment by Kartonrealista** [comment]
There's also #255 where the top of the third row of text is visible even though it shouldn't be, making little dots appear at the bottom of a filename.

**Comment by jackpot51** [comment]
This has been greatly improved in https://github.com/pop-os/cosmic-files/commit/45711e17349da30093a32a6082d361cec07d4db3. Further improvements like ellipsizing should be in a new issue.
