### ISSUE TITLE
[Feature Request] Easy way to create and manage FTP, SFTP, NFS, SMB, SSH, WebDAV, etc shares

### ISSUE THREAD

**Issue by Pentaphon** [pop-os/cosmic-files#71]
I know it's early to ask for this but as a long term goal, cosmic-files should exceed Gnome File's ability to connect to and serve files via all of the open-standard protocols available on Linux desktops in order to connect to other devices on a Pop! user's home network so that we can connect to Windows, Mac and other devices that we can't necessarily install Pop! on. Samba especially is a pain point for people using Ubuntu.

If somebody on the Pop! team could make cosmic-files surpass all other file managers in terms of networking, it would be a real game changer and give people even more reason to use Cosmic over Gnome, Cinnamon, KDE, etc as well as a huge benefit for System76 customers who need a better networking solution for home and professional use cases.

**Comment by WatchMkr** [comment]
tracking here https://github.com/pop-os/cosmic-files/issues/202
