### ISSUE TITLE
Allow opening of properties draw with spacebar.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-files#79]
Currently (dc3c4eb731bc719b4d6ea3c08ac28f5276cae092) is it possible to open the properties for a file through and alternate-click and selecting it from the context menu. 

This contrasts a number of other file managers, such as Apple's "Finder", where file and property previews can be quickly displayed and hidden by tapping `spacebar`. This is also similar to the existing functionality of hitting `enter` to launch the file in the correct default application.

This should make the properties draw both more discoverable, and make previewing and navigating of certain file type - particularly images - more convenient.

**Comment by maria-komarova** [comment]
Seems to me #109 (selecting a file should open the preview) should take care of the need to use the spacebar.

**Comment by iamkartiknayak** [comment]
`Alt + Enter` would make more sense for opening properties of selected items in Cosmic Files.  `space-bar` key can be used to preview supported files or show a snack-bar if it doesn't support selected format for previewing.

**Comment by jackpot51** [comment]
This is implemented
