### ISSUE TITLE
[Feature Request] Delete files from trash

### ISSUE THREAD

**Issue by cd-CreepArghhh** [pop-os/cosmic-files#89]
My assumption is that this is not yet implemented. Trying to do so gives the following error popup:

### Failed operation  
```
Delete {
  paths: [
    "/home/user/Pictures/screenshot.png",
  ],
}
```  
Error during a \`trash\` operation: `FileSystem { path: "/home/user/Pictures/screenshot.png"`, source: `Os { code: 2, kind: NotFound, message: "No such file or directory" } }`

My assumption is that it's trying to delete the original file instead of the one that's in the trash.

(I double checked for this issue to make sure there were no duplicates, hopefully I didn't overlook anything again :D)

**Comment by jackpot51** [comment]
Yeah, this is just not implemented yet.

**Comment by cd-CreepArghhh** [comment]
> Yeah, this is just not implemented yet.

Ah okay, I'm changing the title to feature request then.

**Comment by maria-komarova** [comment]
Maybe we should close that one since I opened a new one with the designs: #110
