### ISSUE TITLE
Cut/Copy/Paste not working

### ISSUE THREAD

**Issue by akialwayz** [pop-os/cosmic-files#90]
As the heading suggests Cut/Copy/Paste (both key combinations and clicking the cut button in right click option) in the file manager.

Only issue is present file manager. File permission are not the problem since I could use a simple cp command without sudo to copy the files.

Situation:
Files were downloaded by Thorium Browser and I couldn't cut and paste the file to different directory.

Delete Works.

Edit:
Also system is up to date.(sudo apt update and upgrade ran in the morning and the system was restarted). 

Specs:
Kernel version: 6.6.10-generic
Cpu- Amd R5 2500U
Ram: 8 Gb
200 GB HDD partition
Dual boot along side Windows.

**Comment by Lonnroth** [comment]
using "Files" within Gnome, i still have this issue, could be permission though.
And i guess it is working within cosmic.

**Comment by joelsolo99** [comment]
I'm also having this issue in gnome but not cosmic: I'd love to be using COSMIC-files already but cosmic doesn't yet support autorotate on my 2-in-1 x360 so I'm stuck with x11 for now :(

**Comment by deroli-us** [comment]
havin the same problem on both my devices. with the gnome file manager everything is working but using cosmic-files i cant copy or paste anything

**Comment by thealanjason** [comment]
Can confirm that it does not work when sing GNOME
